2023-12-23 01:19:13,909:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-23 01:19:13,910:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-23 01:19:13,910:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-23 01:19:13,910:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-23 01:22:43,134:INFO:PyCaret ClassificationExperiment
2023-12-23 01:22:43,135:INFO:Logging name: clf-default-name
2023-12-23 01:22:43,135:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-12-23 01:22:43,135:INFO:version 3.2.0
2023-12-23 01:22:43,135:INFO:Initializing setup()
2023-12-23 01:22:43,135:INFO:self.USI: 9227
2023-12-23 01:22:43,136:INFO:self._variable_keys: {'memory', 'exp_id', 'y_train', 'pipeline', 'log_plots_param', 'is_multiclass', 'y', 'exp_name_log', 'USI', 'fix_imbalance', 'fold_shuffle_param', 'gpu_param', 'y_test', 'data', 'seed', 'X_train', 'idx', 'fold_generator', 'html_param', 'gpu_n_jobs_param', '_ml_usecase', 'logging_param', 'X', '_available_plots', 'X_test', 'fold_groups_param', 'target_param', 'n_jobs_param'}
2023-12-23 01:22:43,136:INFO:Checking environment
2023-12-23 01:22:43,137:INFO:python_version: 3.10.12
2023-12-23 01:22:43,137:INFO:python_build: ('main', 'Nov 20 2023 15:14:05')
2023-12-23 01:22:43,138:INFO:machine: x86_64
2023-12-23 01:22:43,144:INFO:platform: Linux-6.2.0-39-generic-x86_64-with-glibc2.35
2023-12-23 01:22:43,144:INFO:Memory: svmem(total=16598478848, available=2584289280, percent=84.4, used=10607792128, free=855486464, active=1198432256, inactive=10998480896, buffers=135471104, cached=4999729152, shared=3047845888, slab=752304128)
2023-12-23 01:22:43,146:INFO:Physical Core: 4
2023-12-23 01:22:43,147:INFO:Logical Core: 8
2023-12-23 01:22:43,147:INFO:Checking libraries
2023-12-23 01:22:43,147:INFO:System:
2023-12-23 01:22:43,147:INFO:    python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
2023-12-23 01:22:43,147:INFO:executable: /home/ashyr/Desktop/yt/automl/mlenv/bin/python3
2023-12-23 01:22:43,147:INFO:   machine: Linux-6.2.0-39-generic-x86_64-with-glibc2.35
2023-12-23 01:22:43,148:INFO:PyCaret required dependencies:
2023-12-23 01:22:43,193:INFO:                 pip: 22.0.2
2023-12-23 01:22:43,193:INFO:          setuptools: 59.6.0
2023-12-23 01:22:43,194:INFO:             pycaret: 3.2.0
2023-12-23 01:22:43,194:INFO:             IPython: 8.19.0
2023-12-23 01:22:43,194:INFO:          ipywidgets: 8.1.1
2023-12-23 01:22:43,194:INFO:                tqdm: 4.66.1
2023-12-23 01:22:43,195:INFO:               numpy: 1.25.2
2023-12-23 01:22:43,195:INFO:              pandas: 1.5.3
2023-12-23 01:22:43,195:INFO:              jinja2: 3.1.2
2023-12-23 01:22:43,195:INFO:               scipy: 1.10.1
2023-12-23 01:22:43,196:INFO:              joblib: 1.3.2
2023-12-23 01:22:43,196:INFO:             sklearn: 1.2.2
2023-12-23 01:22:43,196:INFO:                pyod: 1.1.2
2023-12-23 01:22:43,196:INFO:            imblearn: 0.11.0
2023-12-23 01:22:43,197:INFO:   category_encoders: 2.6.3
2023-12-23 01:22:43,197:INFO:            lightgbm: 4.2.0
2023-12-23 01:22:43,197:INFO:               numba: 0.58.1
2023-12-23 01:22:43,197:INFO:            requests: 2.31.0
2023-12-23 01:22:43,197:INFO:          matplotlib: 3.6.0
2023-12-23 01:22:43,198:INFO:          scikitplot: 0.3.7
2023-12-23 01:22:43,198:INFO:         yellowbrick: 1.5
2023-12-23 01:22:43,198:INFO:              plotly: 5.18.0
2023-12-23 01:22:43,198:INFO:    plotly-resampler: Not installed
2023-12-23 01:22:43,199:INFO:             kaleido: 0.2.1
2023-12-23 01:22:43,199:INFO:           schemdraw: 0.15
2023-12-23 01:22:43,199:INFO:         statsmodels: 0.14.1
2023-12-23 01:22:43,199:INFO:              sktime: 0.21.1
2023-12-23 01:22:43,199:INFO:               tbats: 1.1.3
2023-12-23 01:22:43,200:INFO:            pmdarima: 2.0.4
2023-12-23 01:22:43,200:INFO:              psutil: 5.9.7
2023-12-23 01:22:43,200:INFO:          markupsafe: 2.1.3
2023-12-23 01:22:43,200:INFO:             pickle5: Not installed
2023-12-23 01:22:43,200:INFO:         cloudpickle: 3.0.0
2023-12-23 01:22:43,201:INFO:         deprecation: 2.1.0
2023-12-23 01:22:43,201:INFO:              xxhash: 3.4.1
2023-12-23 01:22:43,201:INFO:           wurlitzer: 3.0.3
2023-12-23 01:22:43,201:INFO:PyCaret optional dependencies:
2023-12-23 01:22:43,228:INFO:                shap: Not installed
2023-12-23 01:22:43,228:INFO:           interpret: Not installed
2023-12-23 01:22:43,228:INFO:                umap: Not installed
2023-12-23 01:22:43,229:INFO:     ydata_profiling: 4.6.3
2023-12-23 01:22:43,229:INFO:  explainerdashboard: Not installed
2023-12-23 01:22:43,229:INFO:             autoviz: Not installed
2023-12-23 01:22:43,229:INFO:           fairlearn: Not installed
2023-12-23 01:22:43,229:INFO:          deepchecks: Not installed
2023-12-23 01:22:43,230:INFO:             xgboost: Not installed
2023-12-23 01:22:43,230:INFO:            catboost: Not installed
2023-12-23 01:22:43,230:INFO:              kmodes: Not installed
2023-12-23 01:22:43,230:INFO:             mlxtend: Not installed
2023-12-23 01:22:43,231:INFO:       statsforecast: Not installed
2023-12-23 01:22:43,231:INFO:        tune_sklearn: Not installed
2023-12-23 01:22:43,231:INFO:                 ray: Not installed
2023-12-23 01:22:43,231:INFO:            hyperopt: Not installed
2023-12-23 01:22:43,231:INFO:              optuna: Not installed
2023-12-23 01:22:43,232:INFO:               skopt: Not installed
2023-12-23 01:22:43,232:INFO:              mlflow: Not installed
2023-12-23 01:22:43,232:INFO:              gradio: Not installed
2023-12-23 01:22:43,232:INFO:             fastapi: Not installed
2023-12-23 01:22:43,233:INFO:             uvicorn: Not installed
2023-12-23 01:22:43,233:INFO:              m2cgen: Not installed
2023-12-23 01:22:43,233:INFO:           evidently: Not installed
2023-12-23 01:22:43,233:INFO:               fugue: Not installed
2023-12-23 01:22:43,233:INFO:           streamlit: 1.29.0
2023-12-23 01:22:43,234:INFO:             prophet: Not installed
2023-12-23 01:22:43,234:INFO:None
2023-12-23 01:22:43,234:INFO:Set up data.
2023-12-23 01:22:43,252:INFO:Set up folding strategy.
2023-12-23 01:22:43,252:INFO:Set up train/test split.
2023-12-23 01:22:43,266:INFO:Set up index.
2023-12-23 01:22:43,266:INFO:Assigning column types.
2023-12-23 01:22:43,273:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-12-23 01:22:43,349:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-12-23 01:22:43,352:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-23 01:22:43,397:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:43,398:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:43,469:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-12-23 01:22:43,471:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-23 01:22:43,516:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:43,517:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:43,517:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-12-23 01:22:43,572:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-23 01:22:43,608:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:43,609:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:43,658:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-23 01:22:43,687:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:43,687:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:43,688:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-12-23 01:22:43,752:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:43,752:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:43,827:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:43,828:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:43,829:INFO:Preparing preprocessing pipeline...
2023-12-23 01:22:43,838:INFO:Set up simple imputation.
2023-12-23 01:22:43,845:INFO:Set up encoding of ordinal features.
2023-12-23 01:22:43,848:INFO:Set up encoding of categorical features.
2023-12-23 01:22:43,992:INFO:Finished creating preprocessing pipeline.
2023-12-23 01:22:44,015:INFO:Pipeline: Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['PassengerId', 'Pclass', 'Age',
                                             'SibSp', 'Parch', 'Fare'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer'...
                                                              return_df=True,
                                                              use_cat_names=True,
                                                              verbose=0))),
                ('rest_encoding',
                 TransformerWrapper(exclude=None,
                                    include=['Name', 'Ticket', 'Cabin'],
                                    transformer=TargetEncoder(cols=['Name',
                                                                    'Ticket',
                                                                    'Cabin'],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              hierarchy=None,
                                                              min_samples_leaf=20,
                                                              return_df=True,
                                                              smoothing=10,
                                                              verbose=0)))],
         verbose=False)
2023-12-23 01:22:44,015:INFO:Creating final display dataframe.
2023-12-23 01:22:44,399:INFO:Setup _display_container:                     Description             Value
0                    Session id              5862
1                        Target          Survived
2                   Target type            Binary
3           Original data shape         (418, 12)
4        Transformed data shape         (418, 14)
5   Transformed train set shape         (292, 14)
6    Transformed test set shape         (126, 14)
7              Ordinal features                 1
8              Numeric features                 6
9          Categorical features                 5
10     Rows with missing values             79.2%
11                   Preprocess              True
12              Imputation type            simple
13           Numeric imputation              mean
14       Categorical imputation              mode
15     Maximum one-hot encoding                25
16              Encoding method              None
17               Fold Generator   StratifiedKFold
18                  Fold Number                10
19                     CPU Jobs                -1
20                      Use GPU             False
21               Log Experiment             False
22              Experiment Name  clf-default-name
23                          USI              9227
2023-12-23 01:22:44,490:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:44,490:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:44,558:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:44,558:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-23 01:22:44,559:INFO:setup() successfully completed in 1.45s...............
2023-12-23 01:22:44,569:INFO:Initializing compare_models()
2023-12-23 01:22:44,570:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-12-23 01:22:44,570:INFO:Checking exceptions
2023-12-23 01:22:44,574:INFO:Preparing display monitor
2023-12-23 01:22:44,577:INFO:Initializing Logistic Regression
2023-12-23 01:22:44,577:INFO:Total runtime is 1.6768773396809896e-06 minutes
2023-12-23 01:22:44,577:INFO:SubProcess create_model() called ==================================
2023-12-23 01:22:44,578:INFO:Initializing create_model()
2023-12-23 01:22:44,578:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:22:44,578:INFO:Checking exceptions
2023-12-23 01:22:44,578:INFO:Importing libraries
2023-12-23 01:22:44,578:INFO:Copying training dataset
2023-12-23 01:22:44,584:INFO:Defining folds
2023-12-23 01:22:44,584:INFO:Declaring metric variables
2023-12-23 01:22:44,584:INFO:Importing untrained model
2023-12-23 01:22:44,585:INFO:Logistic Regression Imported successfully
2023-12-23 01:22:44,586:INFO:Starting cross validation
2023-12-23 01:22:44,589:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:22:49,589:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-12-23 01:22:49,880:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-12-23 01:22:50,281:INFO:Calculating mean and std
2023-12-23 01:22:50,283:INFO:Creating metrics dataframe
2023-12-23 01:22:50,290:INFO:Uploading results into container
2023-12-23 01:22:50,291:INFO:Uploading model into container now
2023-12-23 01:22:50,292:INFO:_master_model_container: 1
2023-12-23 01:22:50,292:INFO:_display_container: 2
2023-12-23 01:22:50,293:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=5862, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-12-23 01:22:50,293:INFO:create_model() successfully completed......................................
2023-12-23 01:22:50,506:INFO:SubProcess create_model() end ==================================
2023-12-23 01:22:50,506:INFO:Creating metrics dataframe
2023-12-23 01:22:50,516:INFO:Initializing K Neighbors Classifier
2023-12-23 01:22:50,516:INFO:Total runtime is 0.09897993405659994 minutes
2023-12-23 01:22:50,516:INFO:SubProcess create_model() called ==================================
2023-12-23 01:22:50,517:INFO:Initializing create_model()
2023-12-23 01:22:50,517:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:22:50,517:INFO:Checking exceptions
2023-12-23 01:22:50,517:INFO:Importing libraries
2023-12-23 01:22:50,517:INFO:Copying training dataset
2023-12-23 01:22:50,525:INFO:Defining folds
2023-12-23 01:22:50,525:INFO:Declaring metric variables
2023-12-23 01:22:50,526:INFO:Importing untrained model
2023-12-23 01:22:50,526:INFO:K Neighbors Classifier Imported successfully
2023-12-23 01:22:50,527:INFO:Starting cross validation
2023-12-23 01:22:50,530:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:22:51,121:INFO:Calculating mean and std
2023-12-23 01:22:51,121:INFO:Creating metrics dataframe
2023-12-23 01:22:51,125:INFO:Uploading results into container
2023-12-23 01:22:51,126:INFO:Uploading model into container now
2023-12-23 01:22:51,126:INFO:_master_model_container: 2
2023-12-23 01:22:51,127:INFO:_display_container: 2
2023-12-23 01:22:51,127:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-12-23 01:22:51,127:INFO:create_model() successfully completed......................................
2023-12-23 01:22:51,279:INFO:SubProcess create_model() end ==================================
2023-12-23 01:22:51,279:INFO:Creating metrics dataframe
2023-12-23 01:22:51,294:INFO:Initializing Naive Bayes
2023-12-23 01:22:51,295:INFO:Total runtime is 0.11195609569549561 minutes
2023-12-23 01:22:51,295:INFO:SubProcess create_model() called ==================================
2023-12-23 01:22:51,296:INFO:Initializing create_model()
2023-12-23 01:22:51,296:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:22:51,297:INFO:Checking exceptions
2023-12-23 01:22:51,297:INFO:Importing libraries
2023-12-23 01:22:51,297:INFO:Copying training dataset
2023-12-23 01:22:51,305:INFO:Defining folds
2023-12-23 01:22:51,306:INFO:Declaring metric variables
2023-12-23 01:22:51,306:INFO:Importing untrained model
2023-12-23 01:22:51,307:INFO:Naive Bayes Imported successfully
2023-12-23 01:22:51,308:INFO:Starting cross validation
2023-12-23 01:22:51,310:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:22:51,928:INFO:Calculating mean and std
2023-12-23 01:22:51,929:INFO:Creating metrics dataframe
2023-12-23 01:22:51,932:INFO:Uploading results into container
2023-12-23 01:22:51,933:INFO:Uploading model into container now
2023-12-23 01:22:51,933:INFO:_master_model_container: 3
2023-12-23 01:22:51,933:INFO:_display_container: 2
2023-12-23 01:22:51,933:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-12-23 01:22:51,934:INFO:create_model() successfully completed......................................
2023-12-23 01:22:52,088:INFO:SubProcess create_model() end ==================================
2023-12-23 01:22:52,088:INFO:Creating metrics dataframe
2023-12-23 01:22:52,097:INFO:Initializing Decision Tree Classifier
2023-12-23 01:22:52,097:INFO:Total runtime is 0.12532691558202108 minutes
2023-12-23 01:22:52,097:INFO:SubProcess create_model() called ==================================
2023-12-23 01:22:52,098:INFO:Initializing create_model()
2023-12-23 01:22:52,099:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:22:52,099:INFO:Checking exceptions
2023-12-23 01:22:52,099:INFO:Importing libraries
2023-12-23 01:22:52,099:INFO:Copying training dataset
2023-12-23 01:22:52,110:INFO:Defining folds
2023-12-23 01:22:52,110:INFO:Declaring metric variables
2023-12-23 01:22:52,111:INFO:Importing untrained model
2023-12-23 01:22:52,112:INFO:Decision Tree Classifier Imported successfully
2023-12-23 01:22:52,112:INFO:Starting cross validation
2023-12-23 01:22:52,116:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:22:52,529:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:52,574:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:52,584:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:52,585:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:52,644:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:52,680:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:52,681:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:52,740:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:52,828:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:52,852:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:52,870:INFO:Calculating mean and std
2023-12-23 01:22:52,872:INFO:Creating metrics dataframe
2023-12-23 01:22:52,879:INFO:Uploading results into container
2023-12-23 01:22:52,881:INFO:Uploading model into container now
2023-12-23 01:22:52,881:INFO:_master_model_container: 4
2023-12-23 01:22:52,881:INFO:_display_container: 2
2023-12-23 01:22:52,882:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=5862, splitter='best')
2023-12-23 01:22:52,882:INFO:create_model() successfully completed......................................
2023-12-23 01:22:53,051:INFO:SubProcess create_model() end ==================================
2023-12-23 01:22:53,051:INFO:Creating metrics dataframe
2023-12-23 01:22:53,061:INFO:Initializing SVM - Linear Kernel
2023-12-23 01:22:53,061:INFO:Total runtime is 0.14139881531397502 minutes
2023-12-23 01:22:53,061:INFO:SubProcess create_model() called ==================================
2023-12-23 01:22:53,062:INFO:Initializing create_model()
2023-12-23 01:22:53,062:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:22:53,062:INFO:Checking exceptions
2023-12-23 01:22:53,062:INFO:Importing libraries
2023-12-23 01:22:53,062:INFO:Copying training dataset
2023-12-23 01:22:53,069:INFO:Defining folds
2023-12-23 01:22:53,070:INFO:Declaring metric variables
2023-12-23 01:22:53,070:INFO:Importing untrained model
2023-12-23 01:22:53,071:INFO:SVM - Linear Kernel Imported successfully
2023-12-23 01:22:53,071:INFO:Starting cross validation
2023-12-23 01:22:53,073:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:22:53,405:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-23 01:22:53,415:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-23 01:22:53,417:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-23 01:22:53,422:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-23 01:22:53,423:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:53,430:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:53,431:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-23 01:22:53,480:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-23 01:22:53,517:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-23 01:22:53,527:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:53,530:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-23 01:22:53,544:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:53,666:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-23 01:22:53,674:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:53,693:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-23 01:22:53,715:INFO:Calculating mean and std
2023-12-23 01:22:53,716:INFO:Creating metrics dataframe
2023-12-23 01:22:53,722:INFO:Uploading results into container
2023-12-23 01:22:53,724:INFO:Uploading model into container now
2023-12-23 01:22:53,725:INFO:_master_model_container: 5
2023-12-23 01:22:53,726:INFO:_display_container: 2
2023-12-23 01:22:53,726:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=5862, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-12-23 01:22:53,727:INFO:create_model() successfully completed......................................
2023-12-23 01:22:53,954:INFO:SubProcess create_model() end ==================================
2023-12-23 01:22:53,954:INFO:Creating metrics dataframe
2023-12-23 01:22:53,971:INFO:Initializing Ridge Classifier
2023-12-23 01:22:53,972:INFO:Total runtime is 0.15657594601313274 minutes
2023-12-23 01:22:53,973:INFO:SubProcess create_model() called ==================================
2023-12-23 01:22:53,973:INFO:Initializing create_model()
2023-12-23 01:22:53,973:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:22:53,974:INFO:Checking exceptions
2023-12-23 01:22:53,974:INFO:Importing libraries
2023-12-23 01:22:53,974:INFO:Copying training dataset
2023-12-23 01:22:53,986:INFO:Defining folds
2023-12-23 01:22:53,988:INFO:Declaring metric variables
2023-12-23 01:22:53,988:INFO:Importing untrained model
2023-12-23 01:22:53,989:INFO:Ridge Classifier Imported successfully
2023-12-23 01:22:53,990:INFO:Starting cross validation
2023-12-23 01:22:53,994:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:22:54,287:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-23 01:22:54,290:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-23 01:22:54,417:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-23 01:22:54,475:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-23 01:22:54,502:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-23 01:22:54,538:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-23 01:22:54,540:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-23 01:22:54,598:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-23 01:22:54,645:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-23 01:22:54,655:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-23 01:22:54,674:INFO:Calculating mean and std
2023-12-23 01:22:54,676:INFO:Creating metrics dataframe
2023-12-23 01:22:54,683:INFO:Uploading results into container
2023-12-23 01:22:54,684:INFO:Uploading model into container now
2023-12-23 01:22:54,685:INFO:_master_model_container: 6
2023-12-23 01:22:54,685:INFO:_display_container: 2
2023-12-23 01:22:54,686:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=5862, solver='auto',
                tol=0.0001)
2023-12-23 01:22:54,686:INFO:create_model() successfully completed......................................
2023-12-23 01:22:54,861:INFO:SubProcess create_model() end ==================================
2023-12-23 01:22:54,861:INFO:Creating metrics dataframe
2023-12-23 01:22:54,872:INFO:Initializing Random Forest Classifier
2023-12-23 01:22:54,872:INFO:Total runtime is 0.17157862583796185 minutes
2023-12-23 01:22:54,872:INFO:SubProcess create_model() called ==================================
2023-12-23 01:22:54,873:INFO:Initializing create_model()
2023-12-23 01:22:54,873:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:22:54,873:INFO:Checking exceptions
2023-12-23 01:22:54,873:INFO:Importing libraries
2023-12-23 01:22:54,873:INFO:Copying training dataset
2023-12-23 01:22:54,881:INFO:Defining folds
2023-12-23 01:22:54,881:INFO:Declaring metric variables
2023-12-23 01:22:54,881:INFO:Importing untrained model
2023-12-23 01:22:54,882:INFO:Random Forest Classifier Imported successfully
2023-12-23 01:22:54,882:INFO:Starting cross validation
2023-12-23 01:22:54,884:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:22:55,734:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:55,734:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:55,735:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:55,750:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:55,837:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:56,323:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:56,340:INFO:Calculating mean and std
2023-12-23 01:22:56,341:INFO:Creating metrics dataframe
2023-12-23 01:22:56,345:INFO:Uploading results into container
2023-12-23 01:22:56,346:INFO:Uploading model into container now
2023-12-23 01:22:56,346:INFO:_master_model_container: 7
2023-12-23 01:22:56,346:INFO:_display_container: 2
2023-12-23 01:22:56,347:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=5862, verbose=0, warm_start=False)
2023-12-23 01:22:56,347:INFO:create_model() successfully completed......................................
2023-12-23 01:22:56,484:INFO:SubProcess create_model() end ==================================
2023-12-23 01:22:56,484:INFO:Creating metrics dataframe
2023-12-23 01:22:56,492:INFO:Initializing Quadratic Discriminant Analysis
2023-12-23 01:22:56,492:INFO:Total runtime is 0.19858787457148236 minutes
2023-12-23 01:22:56,493:INFO:SubProcess create_model() called ==================================
2023-12-23 01:22:56,493:INFO:Initializing create_model()
2023-12-23 01:22:56,493:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:22:56,493:INFO:Checking exceptions
2023-12-23 01:22:56,493:INFO:Importing libraries
2023-12-23 01:22:56,493:INFO:Copying training dataset
2023-12-23 01:22:56,499:INFO:Defining folds
2023-12-23 01:22:56,500:INFO:Declaring metric variables
2023-12-23 01:22:56,500:INFO:Importing untrained model
2023-12-23 01:22:56,501:INFO:Quadratic Discriminant Analysis Imported successfully
2023-12-23 01:22:56,501:INFO:Starting cross validation
2023-12-23 01:22:56,503:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:22:56,705:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-23 01:22:56,712:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-23 01:22:56,712:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-23 01:22:56,718:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-23 01:22:56,743:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-23 01:22:56,817:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-23 01:22:56,843:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-23 01:22:56,869:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-23 01:22:56,941:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-23 01:22:56,961:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-23 01:22:57,006:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:57,020:INFO:Calculating mean and std
2023-12-23 01:22:57,021:INFO:Creating metrics dataframe
2023-12-23 01:22:57,026:INFO:Uploading results into container
2023-12-23 01:22:57,027:INFO:Uploading model into container now
2023-12-23 01:22:57,027:INFO:_master_model_container: 8
2023-12-23 01:22:57,027:INFO:_display_container: 2
2023-12-23 01:22:57,028:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-12-23 01:22:57,028:INFO:create_model() successfully completed......................................
2023-12-23 01:22:57,160:INFO:SubProcess create_model() end ==================================
2023-12-23 01:22:57,160:INFO:Creating metrics dataframe
2023-12-23 01:22:57,168:INFO:Initializing Ada Boost Classifier
2023-12-23 01:22:57,168:INFO:Total runtime is 0.2098507086435954 minutes
2023-12-23 01:22:57,168:INFO:SubProcess create_model() called ==================================
2023-12-23 01:22:57,169:INFO:Initializing create_model()
2023-12-23 01:22:57,169:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:22:57,169:INFO:Checking exceptions
2023-12-23 01:22:57,169:INFO:Importing libraries
2023-12-23 01:22:57,170:INFO:Copying training dataset
2023-12-23 01:22:57,176:INFO:Defining folds
2023-12-23 01:22:57,176:INFO:Declaring metric variables
2023-12-23 01:22:57,177:INFO:Importing untrained model
2023-12-23 01:22:57,177:INFO:Ada Boost Classifier Imported successfully
2023-12-23 01:22:57,178:INFO:Starting cross validation
2023-12-23 01:22:57,180:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:22:57,502:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:57,604:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:57,683:INFO:Calculating mean and std
2023-12-23 01:22:57,684:INFO:Creating metrics dataframe
2023-12-23 01:22:57,689:INFO:Uploading results into container
2023-12-23 01:22:57,690:INFO:Uploading model into container now
2023-12-23 01:22:57,691:INFO:_master_model_container: 9
2023-12-23 01:22:57,692:INFO:_display_container: 2
2023-12-23 01:22:57,692:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=5862)
2023-12-23 01:22:57,693:INFO:create_model() successfully completed......................................
2023-12-23 01:22:57,828:INFO:SubProcess create_model() end ==================================
2023-12-23 01:22:57,828:INFO:Creating metrics dataframe
2023-12-23 01:22:57,839:INFO:Initializing Gradient Boosting Classifier
2023-12-23 01:22:57,839:INFO:Total runtime is 0.22103591759999594 minutes
2023-12-23 01:22:57,840:INFO:SubProcess create_model() called ==================================
2023-12-23 01:22:57,840:INFO:Initializing create_model()
2023-12-23 01:22:57,840:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:22:57,840:INFO:Checking exceptions
2023-12-23 01:22:57,841:INFO:Importing libraries
2023-12-23 01:22:57,841:INFO:Copying training dataset
2023-12-23 01:22:57,848:INFO:Defining folds
2023-12-23 01:22:57,848:INFO:Declaring metric variables
2023-12-23 01:22:57,849:INFO:Importing untrained model
2023-12-23 01:22:57,849:INFO:Gradient Boosting Classifier Imported successfully
2023-12-23 01:22:57,850:INFO:Starting cross validation
2023-12-23 01:22:57,852:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:22:58,474:INFO:Calculating mean and std
2023-12-23 01:22:58,475:INFO:Creating metrics dataframe
2023-12-23 01:22:58,478:INFO:Uploading results into container
2023-12-23 01:22:58,479:INFO:Uploading model into container now
2023-12-23 01:22:58,479:INFO:_master_model_container: 10
2023-12-23 01:22:58,479:INFO:_display_container: 2
2023-12-23 01:22:58,480:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=5862, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-12-23 01:22:58,480:INFO:create_model() successfully completed......................................
2023-12-23 01:22:58,624:INFO:SubProcess create_model() end ==================================
2023-12-23 01:22:58,624:INFO:Creating metrics dataframe
2023-12-23 01:22:58,634:INFO:Initializing Linear Discriminant Analysis
2023-12-23 01:22:58,635:INFO:Total runtime is 0.23429157733917239 minutes
2023-12-23 01:22:58,635:INFO:SubProcess create_model() called ==================================
2023-12-23 01:22:58,636:INFO:Initializing create_model()
2023-12-23 01:22:58,636:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:22:58,636:INFO:Checking exceptions
2023-12-23 01:22:58,636:INFO:Importing libraries
2023-12-23 01:22:58,636:INFO:Copying training dataset
2023-12-23 01:22:58,643:INFO:Defining folds
2023-12-23 01:22:58,644:INFO:Declaring metric variables
2023-12-23 01:22:58,644:INFO:Importing untrained model
2023-12-23 01:22:58,644:INFO:Linear Discriminant Analysis Imported successfully
2023-12-23 01:22:58,645:INFO:Starting cross validation
2023-12-23 01:22:58,647:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:22:58,948:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:58,966:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:58,993:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:59,000:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:59,035:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:59,094:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:59,106:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:59,139:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:59,211:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:59,242:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:22:59,251:INFO:Calculating mean and std
2023-12-23 01:22:59,253:INFO:Creating metrics dataframe
2023-12-23 01:22:59,259:INFO:Uploading results into container
2023-12-23 01:22:59,261:INFO:Uploading model into container now
2023-12-23 01:22:59,262:INFO:_master_model_container: 11
2023-12-23 01:22:59,262:INFO:_display_container: 2
2023-12-23 01:22:59,263:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-12-23 01:22:59,263:INFO:create_model() successfully completed......................................
2023-12-23 01:22:59,427:INFO:SubProcess create_model() end ==================================
2023-12-23 01:22:59,428:INFO:Creating metrics dataframe
2023-12-23 01:22:59,441:INFO:Initializing Extra Trees Classifier
2023-12-23 01:22:59,441:INFO:Total runtime is 0.24772719542185467 minutes
2023-12-23 01:22:59,441:INFO:SubProcess create_model() called ==================================
2023-12-23 01:22:59,442:INFO:Initializing create_model()
2023-12-23 01:22:59,442:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:22:59,442:INFO:Checking exceptions
2023-12-23 01:22:59,442:INFO:Importing libraries
2023-12-23 01:22:59,443:INFO:Copying training dataset
2023-12-23 01:22:59,451:INFO:Defining folds
2023-12-23 01:22:59,451:INFO:Declaring metric variables
2023-12-23 01:22:59,451:INFO:Importing untrained model
2023-12-23 01:22:59,452:INFO:Extra Trees Classifier Imported successfully
2023-12-23 01:22:59,453:INFO:Starting cross validation
2023-12-23 01:22:59,455:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:23:00,471:INFO:Calculating mean and std
2023-12-23 01:23:00,472:INFO:Creating metrics dataframe
2023-12-23 01:23:00,477:INFO:Uploading results into container
2023-12-23 01:23:00,478:INFO:Uploading model into container now
2023-12-23 01:23:00,478:INFO:_master_model_container: 12
2023-12-23 01:23:00,478:INFO:_display_container: 2
2023-12-23 01:23:00,479:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=5862, verbose=0, warm_start=False)
2023-12-23 01:23:00,479:INFO:create_model() successfully completed......................................
2023-12-23 01:23:00,613:INFO:SubProcess create_model() end ==================================
2023-12-23 01:23:00,614:INFO:Creating metrics dataframe
2023-12-23 01:23:00,621:INFO:Initializing Light Gradient Boosting Machine
2023-12-23 01:23:00,621:INFO:Total runtime is 0.26740525563557943 minutes
2023-12-23 01:23:00,622:INFO:SubProcess create_model() called ==================================
2023-12-23 01:23:00,622:INFO:Initializing create_model()
2023-12-23 01:23:00,622:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:23:00,623:INFO:Checking exceptions
2023-12-23 01:23:00,623:INFO:Importing libraries
2023-12-23 01:23:00,623:INFO:Copying training dataset
2023-12-23 01:23:00,629:INFO:Defining folds
2023-12-23 01:23:00,630:INFO:Declaring metric variables
2023-12-23 01:23:00,630:INFO:Importing untrained model
2023-12-23 01:23:00,631:INFO:Light Gradient Boosting Machine Imported successfully
2023-12-23 01:23:00,632:INFO:Starting cross validation
2023-12-23 01:23:00,634:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:26:41,115:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:26:45,286:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:26:47,516:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:26:48,579:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:26:50,463:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:26:54,170:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:26:55,013:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:26:55,997:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:27:51,054:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:27:51,135:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:27:51,145:INFO:Calculating mean and std
2023-12-23 01:27:51,146:INFO:Creating metrics dataframe
2023-12-23 01:27:51,149:INFO:Uploading results into container
2023-12-23 01:27:51,150:INFO:Uploading model into container now
2023-12-23 01:27:51,150:INFO:_master_model_container: 13
2023-12-23 01:27:51,150:INFO:_display_container: 2
2023-12-23 01:27:51,151:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=5862, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-12-23 01:27:51,151:INFO:create_model() successfully completed......................................
2023-12-23 01:27:51,286:INFO:SubProcess create_model() end ==================================
2023-12-23 01:27:51,286:INFO:Creating metrics dataframe
2023-12-23 01:27:51,294:INFO:Initializing Dummy Classifier
2023-12-23 01:27:51,295:INFO:Total runtime is 5.111957188447317 minutes
2023-12-23 01:27:51,295:INFO:SubProcess create_model() called ==================================
2023-12-23 01:27:51,295:INFO:Initializing create_model()
2023-12-23 01:27:51,295:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f9bfe1d26e0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:27:51,296:INFO:Checking exceptions
2023-12-23 01:27:51,296:INFO:Importing libraries
2023-12-23 01:27:51,296:INFO:Copying training dataset
2023-12-23 01:27:51,303:INFO:Defining folds
2023-12-23 01:27:51,303:INFO:Declaring metric variables
2023-12-23 01:27:51,304:INFO:Importing untrained model
2023-12-23 01:27:51,305:INFO:Dummy Classifier Imported successfully
2023-12-23 01:27:51,305:INFO:Starting cross validation
2023-12-23 01:27:51,308:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-23 01:27:51,589:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:27:51,594:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:27:51,597:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:27:51,602:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:27:51,604:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:27:51,696:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:27:51,708:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:27:51,709:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:27:51,758:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:27:51,780:WARNING:/home/ashyr/Desktop/yt/automl/mlenv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-23 01:27:51,795:INFO:Calculating mean and std
2023-12-23 01:27:51,796:INFO:Creating metrics dataframe
2023-12-23 01:27:51,800:INFO:Uploading results into container
2023-12-23 01:27:51,801:INFO:Uploading model into container now
2023-12-23 01:27:51,801:INFO:_master_model_container: 14
2023-12-23 01:27:51,801:INFO:_display_container: 2
2023-12-23 01:27:51,802:INFO:DummyClassifier(constant=None, random_state=5862, strategy='prior')
2023-12-23 01:27:51,802:INFO:create_model() successfully completed......................................
2023-12-23 01:27:51,943:INFO:SubProcess create_model() end ==================================
2023-12-23 01:27:51,943:INFO:Creating metrics dataframe
2023-12-23 01:27:51,954:INFO:Initializing create_model()
2023-12-23 01:27:51,954:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f9bfe2da9e0>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=5862, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-23 01:27:51,955:INFO:Checking exceptions
2023-12-23 01:27:51,956:INFO:Importing libraries
2023-12-23 01:27:51,956:INFO:Copying training dataset
2023-12-23 01:27:51,963:INFO:Defining folds
2023-12-23 01:27:51,963:INFO:Declaring metric variables
2023-12-23 01:27:51,964:INFO:Importing untrained model
2023-12-23 01:27:51,964:INFO:Declaring custom model
2023-12-23 01:27:51,965:INFO:Logistic Regression Imported successfully
2023-12-23 01:27:51,968:INFO:Cross validation set to False
2023-12-23 01:27:51,968:INFO:Fitting Model
2023-12-23 01:27:52,192:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=5862, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-12-23 01:27:52,192:INFO:create_model() successfully completed......................................
2023-12-23 01:27:52,354:INFO:_master_model_container: 14
2023-12-23 01:27:52,354:INFO:_display_container: 2
2023-12-23 01:27:52,355:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=5862, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-12-23 01:27:52,355:INFO:compare_models() successfully completed......................................
2023-12-23 01:27:52,401:INFO:Initializing save_model()
2023-12-23 01:27:52,402:INFO:save_model(model=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=5862, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), model_name=trained_model, prep_pipe_=Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['PassengerId', 'Pclass', 'Age',
                                             'SibSp', 'Parch', 'Fare'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer'...
                                                              return_df=True,
                                                              use_cat_names=True,
                                                              verbose=0))),
                ('rest_encoding',
                 TransformerWrapper(exclude=None,
                                    include=['Name', 'Ticket', 'Cabin'],
                                    transformer=TargetEncoder(cols=['Name',
                                                                    'Ticket',
                                                                    'Cabin'],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              hierarchy=None,
                                                              min_samples_leaf=20,
                                                              return_df=True,
                                                              smoothing=10,
                                                              verbose=0)))],
         verbose=False), verbose=True, use_case=MLUsecase.CLASSIFICATION, kwargs={})
2023-12-23 01:27:52,402:INFO:Adding model into prep_pipe
2023-12-23 01:27:52,423:INFO:trained_model.pkl saved in current working directory
2023-12-23 01:27:52,459:INFO:Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['PassengerId', 'Pclass', 'Age',
                                             'SibSp', 'Parch', 'Fare'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 Transforme...
                                                              handle_unknown='value',
                                                              hierarchy=None,
                                                              min_samples_leaf=20,
                                                              return_df=True,
                                                              smoothing=10,
                                                              verbose=0))),
                ('trained_model',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=1000,
                                    multi_class='auto', n_jobs=None,
                                    penalty='l2', random_state=5862,
                                    solver='lbfgs', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)
2023-12-23 01:27:52,459:INFO:save_model() successfully completed......................................
